# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 474f1250b8194c4b8b98071b73d36dd1f9df690b12c79790307860540a13c92db1f5eb2257392413524a579bfee25a5abd68e38803b6143adaa68ff354698e6b

test:
  secret_key_base: 9f3f4ace304cf06ca40c0b1a72b2c31f1f18c7a084da5b355981effe8345bad107d422cf060c55976ea32e49591b6644a71d3ccd7e49ecb93315cefcd006bbeb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
